"""Add Tag model

Revision ID: 0906a26c2f98
Revises: 5f12e54460e3
Create Date: 2024-12-08 23:21:47.408534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0906a26c2f98'
down_revision = '5f12e54460e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_post_tags_tag_id', 'tags', ['tag_id'], ['id'])

    # ### end Alembic commands ###


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tag_id')

    # ### end Alembic commands ###
